name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4

      - name: Gerar animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AngelicaDev17
          outputs: |
            dist/snake.svg

      - name: Commit do arquivo gerado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizando animação Snake"
          branch: output
          file_pattern: dist/snake.svg


